FROM nginx:1.18.0

RUN apt-get update

# configuration
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf


# Append "daemon off;" to the beginning of the configuration
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

EXPOSE 80

CMD service nginx-debug start

